=== hekimoghlu/OpenSystem/src/DE/dasher/Data/control/control.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT control ((node|alph)*)>
<!ATTLIST control name CDATA #REQUIRED>

<!ELEMENT node ((node|move|delete|copy|speak|pause|stop|ref|root|alph)*)>
<!--by specifying the name attribute as type ID rather than CDATA, the XML
    validator checks that all IDs are distinct:-->
<!ATTLIST node name ID #IMPLIED>
<!ATTLIST node label CDATA #REQUIRED>
<!ATTLIST node color CDATA #IMPLIED>

<!ELEMENT move EMPTY>
<!ATTLIST move forward (yes|no) #REQUIRED>
<!ATTLIST move dist (char|word|line|sentence|paragraph|page|all) #REQUIRED>

<!ELEMENT delete EMPTY>
<!ATTLIST delete forward (yes|no) #REQUIRED>
<!ATTLIST delete dist (char|word|line|sentence|paragraph|page|all) #REQUIRED>

<!ELEMENT copy EMPTY>
<!ATTLIST copy what (new|repeat|word|line|sentence|paragraph|page|all) #REQUIRED>

<!ELEMENT speak EMPTY>
<!ATTLIST speak what (cancel|new|repeat|word|line|sentence|paragraph|page|all) #REQUIRED>

<!ELEMENT pause EMPTY>

<!ELEMENT stop EMPTY>

<!ELEMENT ref EMPTY>
<!--by specifying the name attribute as type IDREF rather than CDATA, the XML
    validator checks that a node with that name (as an ID) exists-->
<!ATTLIST ref name IDREF #REQUIRED>

<!ELEMENT root EMPTY>

<!ELEMENT alph EMPTY>

=== hekimoghlu/OpenSystem/src/DE/dasher/Data/control/control.edit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE control SYSTEM "control.dtd">
<control name="Edit Larger Document (symbols)">
  <alph/>
  
  <node label="&#9209;" color="242">
    <stop/>
    <alph/>
    <root/>
  </node>

  <node name="CTL_MOVE" label="&#10018;" color="-1">
    <node name="CTL_MOVE_BACKWARD" label="&#8678;" color="-1">
      <node label="&#128464;" color="-1">
        <move forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <move forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <move forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <move forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#8226;" color="-1">
        <move forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_MOVE_FORWARD" label="&#8680;" color="-1">

      <node label="&#8226;" color="-1">
        <move forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <move forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <move forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <move forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#128464;" color="-1">
        <move forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

  </node>
  
  <node name="CTL_DELETE" label="&#10683;" color="-1">
    <node name="CTL_DELETE_BACKWARD" label="&#9003;" color="-1">
      <node label="&#128464;" color="-1">
        <delete forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <delete forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <delete forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <delete forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#8226;" color="-1">
        <delete forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_DELETE_FORWARD" label="&#8998;" color="-1">

      <node label="&#8226;" color="-1">
        <delete forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <delete forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <delete forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <delete forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#128464;" color="-1">
        <delete forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>
  </node>

  <alph/>
  
</control>

=== hekimoghlu/OpenSystem/src/DE/dasher/Data/control/control.edit.txt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE control SYSTEM "control.dtd">
<control name="Edit Larger Document (ascii)">
  <alph/>
  
  <node label="Stop" color="242">
    <stop/>
    <alph/>
    <root/>
  </node>

  <node name="CTL_MOVE" label="Move" color="-1">
    <node name="CTL_MOVE_BACKWARD" label="&lt;=" color="-1">
      <node label="All" color="-1">
        <move forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Para." color="-1">
        <move forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Sent." color="-1">
        <move forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Word" color="-1">
        <move forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Char" color="-1">
        <move forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_MOVE_FORWARD" label="=&gt;" color="-1">

      <node label="Char" color="-1">
        <move forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Word" color="-1">
        <move forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Sent." color="-1">
        <move forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Para." color="-1">
        <move forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="All" color="-1">
        <move forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

  </node>
  
  <node name="CTL_DELETE" label="Delete" color="-1">
    <node name="CTL_DELETE_BACKWARD" label="&lt;x" color="-1">
      <node label="All" color="-1">
        <delete forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Para." color="-1">
        <delete forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Sent." color="-1">
        <delete forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Word" color="-1">
        <delete forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Char" color="-1">
        <delete forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_DELETE_FORWARD" label="x&gt;" color="-1">

      <node label="Char" color="-1">
        <delete forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Word" color="-1">
        <delete forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Sent." color="-1">
        <delete forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Para." color="-1">
        <delete forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="All" color="-1">
        <delete forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>
  </node>

  <alph/>
  
</control>

=== hekimoghlu/OpenSystem/src/DE/dasher/Data/control/control.speak.txt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE control SYSTEM "control.dtd">
<control name="Conversation (ascii)">
  

  <node name="CTL_MOVE" label="Move" color="-1">
    <alph/>
    <node name="CTL_MOVE_BACKWARD" label="&lt;=" color="-1">
      <node label="All" color="-1">
        <move forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Para." color="-1">
        <move forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Sent." color="-1">
        <move forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Word" color="-1">
        <move forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Char" color="-1">
        <move forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_MOVE_FORWARD" label="=&gt;" color="-1">

      <node label="Char" color="-1">
        <move forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Word" color="-1">
        <move forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Sent." color="-1">
        <move forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="Para." color="-1">
        <move forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="All" color="-1">
        <move forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

    
  </node>
  <node name="CTL_DELETE" label="Delete" color="-1">
    <alph/>
    <node name="CTL_DELETE_BACKWARD" label="&lt;x" color="-1">
      <node label="All" color="-1">
        <delete forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Para." color="-1">
        <delete forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Sent." color="-1">
        <delete forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Word" color="-1">
        <delete forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Char" color="-1">
        <delete forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_DELETE_FORWARD" label="x&gt;" color="-1">

      <node label="Char" color="-1">
        <delete forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Word" color="-1">
        <delete forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Sent." color="-1">
        <delete forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="Para." color="-1">
        <delete forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="All" color="-1">
        <delete forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>


  </node>
  <node name="CTL_CLEAR" label="Clear" color="-1">
    <alph/>
    <node label="All" color="242">
      <delete forward="yes" dist="all"/>
      <delete forward="no" dist="all"/>
      <alph/>
      <root/>
    </node>
    <alph/>
  </node>

  <node  name="CTL_SPEAK" label="Speak" color="241">

    <node label="Stop" color="242">
      <speak what="cancel"/>
      <alph/>
      <root/>
    </node>
    <node label="Repeat" color="241">
      <speak what="repeat"/>
      <alph/>
      <root/>
    </node>
    <node label="Para." color="-1">
      <speak what="paragraph"/>
      <move forward="yes" dist="paragraph"/>
      <alph/>
      <node  name="CTL_SPEAK_PARAGRAPH2" label="SpeakPara." color="-1">
        <speak what="paragraph"/>
        <move forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_SPEAK_PARAGRAPH2"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <node label="ClearPara." color="242">
        <!--Delete previous paragraph and CRLF characters. -->
        <delete forward="no" dist="paragraph"/>
        <delete forward="no" dist="char"/>
        <delete forward="no" dist="char"/>
        <alph/>
        <root/>
      </node>
      <ref name="CTL_SPEAK"/>
    </node>
    <node label="All" color="-1">
      <speak what="all"/>
      <move forward="yes" dist="all"/>
      <alph/>
      <node label="ClearAll" color="242">
        <delete forward="yes" dist="all"/>
        <delete forward="no" dist="all"/>
        <alph/>
        <root/>
      </node>
      <ref name="CTL_SPEAK"/>
    </node>
    <alph/>
  </node>

</control>

=== hekimoghlu/OpenSystem/src/DE/dasher/Data/control/control.prepared_speech.txt.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE control SYSTEM "control.dtd">
<control name="Speak From Prepared Document (ascii)">

  <node name="CTL_MOVE" label="Move" color="-1">
    
    <node name="CTL_MOVE_BACKWARD" label="&lt;=" color="-1">
      <node label="All" color="-1">
        <move forward="no" dist="all"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <node label="Para." color="-1">
        <move forward="no" dist="paragraph"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <node label="Sent." color="-1">
        <move forward="no" dist="sentence"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
    </node>

    <node name="CTL_MOVE_FORWARD" label="=&gt;" color="-1">

      <node label="Sent." color="-1">
        <move forward="yes" dist="sentence"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <node label="Para." color="-1">
        <move forward="yes" dist="paragraph"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <node label="All" color="-1">
        <move forward="yes" dist="all"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
    </node>
  </node>

  <node  name="CTL_SPEAK" label="Speak" color="241">

    <node label="Stop" color="242">
      <speak what="cancel"/>
      <ref name="CTL_MOVE"/>
      <ref name="CTL_SPEAK"/>
    </node>
    <node label="Repeat" color="241">
      <speak what="repeat"/>
      <ref name="CTL_MOVE"/>
      <ref name="CTL_SPEAK"/>
    </node>
    <node label="Sent." color="-1">
      <speak what="sentence"/>
      <move forward="yes" dist="sentence"/>
      <ref name="CTL_MOVE"/>
      <ref name="CTL_SPEAK"/>
    </node>
    <node label="Para." color="-1">
      <speak what="paragraph"/>
      <move forward="yes" dist="paragraph"/>
      <ref name="CTL_MOVE"/>
      <ref name="CTL_SPEAK"/>
    </node>
  </node>
</control>

=== hekimoghlu/OpenSystem/src/DE/dasher/Data/control/control.prepared_speech.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE control SYSTEM "control.dtd">
<control name="Speak From Prepared Document (symbols)">

  <node name="CTL_MOVE" label="&#10018;" color="-1">
    
    <node name="CTL_MOVE_BACKWARD" label="&#8678;" color="-1">
      <node label="&#128464;" color="-1">
        <move forward="no" dist="all"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <node label="&#182;" color="-1">
        <move forward="no" dist="paragraph"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <node label=".&#8265;" color="-1">
        <move forward="no" dist="sentence"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
    </node>

    <node name="CTL_MOVE_FORWARD" label="&#8680;" color="-1">

      <node label=".&#8265;" color="-1">
        <move forward="yes" dist="sentence"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <node label="&#182;" color="-1">
        <move forward="yes" dist="paragraph"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <node label="&#128464;" color="-1">
        <move forward="yes" dist="all"/>
        <ref name="CTL_MOVE"/>
        <ref name="CTL_SPEAK"/>
      </node>
    </node>
  </node>

  <node  name="CTL_SPEAK" label="&#128483;" color="241">

    <node label="&#9209;" color="242">
      <speak what="cancel"/>
      <ref name="CTL_MOVE"/>
      <ref name="CTL_SPEAK"/>
    </node>
    <node label="&#128259;" color="241">
      <speak what="repeat"/>
      <ref name="CTL_MOVE"/>
      <ref name="CTL_SPEAK"/>
    </node>
    <node label=".&#8265;" color="-1">
      <speak what="sentence"/>
      <move forward="yes" dist="sentence"/>
      <ref name="CTL_MOVE"/>
      <ref name="CTL_SPEAK"/>
    </node>
    <node label="&#182;" color="-1">
      <speak what="paragraph"/>
      <move forward="yes" dist="paragraph"/>
      <ref name="CTL_MOVE"/>
      <ref name="CTL_SPEAK"/>
    </node>
  </node>
</control>

=== hekimoghlu/OpenSystem/src/DE/dasher/Data/control/control.all.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE control SYSTEM "control.dtd">
<control name="All Available Commands (symbols)">
  <alph/>
  
  <node label="&#9209;" color="242">
    <stop/>
    <alph/>
    <root/>
  </node>

  <node label="&#9208;" color="241">
    <pause/>
    <alph/>
    <root/>
  </node>

  <node name="CTL_MOVE" label="&#10018;" color="-1">
    <node name="CTL_MOVE_BACKWARD" label="&#8678;" color="-1">
      <node label="&#128464;" color="-1">
        <move forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <move forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <move forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#9473;" color="-1">
        <move forward="no" dist="line"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <move forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#8226;" color="-1">
        <move forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_MOVE_FORWARD" label="&#8680;" color="-1">

      <node label="&#8226;" color="-1">
        <move forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <move forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#9473;" color="-1">
        <move forward="yes" dist="line"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>   
      <node label=".&#8265;" color="-1">
        <move forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <move forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#128464;" color="-1">
        <move forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

  </node>
  
  <node name="CTL_DELETE" label="&#10683;" color="-1">
    <node name="CTL_DELETE_BACKWARD" label="&#9003;" color="-1">
      <node label="&#128464;" color="-1">
        <delete forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <delete forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <delete forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#9473;" color="-1">
        <delete forward="no" dist="line"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <delete forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#8226;" color="-1">
        <delete forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_DELETE_FORWARD" label="&#8998;" color="-1">

      <node label="&#8226;" color="-1">
        <delete forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <delete forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#9473;" color="-1">
        <delete forward="yes" dist="line"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <delete forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <delete forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#128464;" color="-1">
        <delete forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>
  </node>

  <node name="CTL_CLEAR" label="&#9114;" color="-1">
    <alph/>
    <node label="&#128464;" color="242">
      <delete forward="yes" dist="all"/>
      <delete forward="no" dist="all"/>
      <alph/>
      <root/>
    </node>
    <alph/>
  </node>
 
  <node  name="CTL_COPY" label="&#128203;" color="-1">

    <node label="&#128259;" color="-1">
      <copy what="repeat"/>
      <alph/>
      <root/>
    </node>
    <node label="&#11052;" color="-1">
      <copy what="word"/>
      <alph/>
      <root/>
    </node>
    <node label="&#9473;" color="-1">
      <copy what="line"/>
      <alph/>
      <root/>
    </node>
    <node label=".&#8265;" color="-1">
      <copy what="sentence"/>
      <alph/>
      <root/>
    </node>
    <node label="&#182;" color="-1">
      <copy what="paragraph"/>
      <alph/>
      <root/>
    </node>
    <node label="&#127381;" color="-1">
      <copy what="new"/>
      <alph/>
      <root/>
    </node>
    <node label="&#128464;" color="-1">
      <copy what="all"/>
      <alph/>
      <root/>
    </node>
  </node>

  <node  name="CTL_SPEAK" label="&#128483;" color="241">
    <node label="&#9209;" color="242">
      <speak what="cancel"/>
      <alph/>
      <root/>
    </node>
    <node label="&#128259;" color="241">
      <speak what="repeat"/>
      <alph/>
      <root/>
    </node>
    <node label="&#11052;" color="-1">
      <speak what="word"/>
      <move forward="yes" dist="word"/>
      <alph/>
      <root/>
    </node>
    <node label="&#9473;" color="-1">
      <speak what="line"/>
      <move forward="yes" dist="line"/>
      <alph/>
      <root/>
    </node>
    <node label=".&#8265;" color="-1">
      <speak what="sentence"/>
      <move forward="yes" dist="sentence"/>
      <alph/>
      <root/>
    </node>
    <node label="&#182;" color="-1">
      <speak what="paragraph"/>
      <move forward="yes" dist="paragraph"/>
      <alph/>
        <root/>
      </node>
    <node label="&#127381;" color="-1">
      <speak what="new"/>
      <move forward="yes" dist="all"/>
      <alph/>
      <root/>
    </node>
    <node label="&#128464;" color="-1">
      <speak what="all"/>
      <move forward="yes" dist="all"/>
      <alph/>
      <root/>
    </node>
  </node>

  <alph/>
  
  <!--
  <node label="utf symbols" color="241">
    <node label="&#128263;&#128172;&#128266;&#128265;&#128264;&#8635;&#9477;&#9473;&#9549;&#11097;&#8265;" color="242">
      <alph/>
      <root/>
    </node>
    <node label="&#9114;&#9112;&#9111;&#9100;&#9086;&#9003;	&#8999;&#8998;&#128711;&#8210;&#10683;" color="242">
      <alph/>
      <root/>
    </node>
    <node label="&#128483;&#128471;&#128470;&#128469;&#128276;&#128259;&#128257;&#128227;&#128463;&#128464;" color="242">
      <alph/>
      <root/>
    </node>
    <node label="&#128203;&#128193;&#128190;&#10008;&#9986;&#9888;&#9776;&#9477;&#11052;&#9679;&#8226;" color="242">
      <alph/>
      <root/>
    </node>
       <node label="&#128203;&#128193;&#128190;&#10008;&#9986;&#9888;&#9776;&#9477;&#11052;&#9679;&#8226;" color="242">
      <alph/>
         <root/>
       </node>
    <node label="&#8678;&#128712;&#128479;&#10561;&#10227;&#8680;&#8596;&#127381;" color="242">
      <alph/>
      <root/>
    </node>
  </node>
  -->
</control>
