=== hekimoghlu/OpenSystem/src/DE/dasher/Data/control/control.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT control ((node|alph)*)>
<!ATTLIST control name CDATA #REQUIRED>

<!ELEMENT node ((node|move|delete|copy|speak|pause|stop|ref|root|alph)*)>
<!--by specifying the name attribute as type ID rather than CDATA, the XML
    validator checks that all IDs are distinct:-->
<!ATTLIST node name ID #IMPLIED>
<!ATTLIST node label CDATA #REQUIRED>
<!ATTLIST node color CDATA #IMPLIED>

<!ELEMENT move EMPTY>
<!ATTLIST move forward (yes|no) #REQUIRED>
<!ATTLIST move dist (char|word|line|sentence|paragraph|page|all) #REQUIRED>

<!ELEMENT delete EMPTY>
<!ATTLIST delete forward (yes|no) #REQUIRED>
<!ATTLIST delete dist (char|word|line|sentence|paragraph|page|all) #REQUIRED>

<!ELEMENT copy EMPTY>
<!ATTLIST copy what (new|repeat|word|line|sentence|paragraph|page|all) #REQUIRED>

<!ELEMENT speak EMPTY>
<!ATTLIST speak what (cancel|new|repeat|word|line|sentence|paragraph|page|all) #REQUIRED>

<!ELEMENT pause EMPTY>

<!ELEMENT stop EMPTY>

<!ELEMENT ref EMPTY>
<!--by specifying the name attribute as type IDREF rather than CDATA, the XML
    validator checks that a node with that name (as an ID) exists-->
<!ATTLIST ref name IDREF #REQUIRED>

<!ELEMENT root EMPTY>

<!ELEMENT alph EMPTY>

=== hekimoghlu/OpenSystem/src/DE/dasher/Data/control/control.generic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE control SYSTEM "control.dtd">
<control name="Default (symbols)">
  <alph/>

  <node label="&#9209;" color="242">
    <stop/>
    <alph/>
    <root/>
  </node>

  <node label="&#9208;" color="241">
    <pause/>
    <alph/>
    <root/>
  </node>

  <node name="CTL_MOVE" label="&#10018;" color="-1">
    <alph/>
    <node name="CTL_MOVE_BACKWARD" label="&#8678;" color="-1">
      <node label="&#128464;" color="-1">
        <move forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <move forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <move forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <move forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#8226;" color="-1">
        <move forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_MOVE_FORWARD" label="&#8680;" color="-1">

      <node label="&#8226;" color="-1">
        <move forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <move forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <move forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <move forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
      <node label="&#128464;" color="-1">
        <move forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_MOVE_BACKWARD"/>
        <ref name="CTL_MOVE_FORWARD"/>
      </node>
    </node>

    
  </node>
  <node name="CTL_DELETE" label="&#10683;" color="-1">
    <alph/>
    <node name="CTL_DELETE_BACKWARD" label="&#9003;" color="-1">
      <node label="&#128464;" color="-1">
        <delete forward="no" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <delete forward="no" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <delete forward="no" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <delete forward="no" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#8226;" color="-1">
        <delete forward="no" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>

    <node name="CTL_DELETE_FORWARD" label="&#8998;" color="-1">

      <node label="&#8226;" color="-1">
        <delete forward="yes" dist="char"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#11052;" color="-1">
        <delete forward="yes" dist="word"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label=".&#8265;" color="-1">
        <delete forward="yes" dist="sentence"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#182;" color="-1">
        <delete forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
      <node label="&#128464;" color="-1">
        <delete forward="yes" dist="all"/>
        <alph/>
        <ref name="CTL_DELETE_BACKWARD"/>
        <ref name="CTL_DELETE_FORWARD"/>
      </node>
    </node>


  </node>
  <node name="CTL_CLEAR" label="&#9114;" color="-1">
    <alph/>
    <node label="&#128464;" color="242">
      <delete forward="yes" dist="all"/>
      <delete forward="no" dist="all"/>
      <alph/>
      <root/>
    </node>
    <alph/>
  </node>

  <node  name="CTL_SPEAK" label="&#128483;" color="241">

    <node label="&#9209;" color="242">
      <speak what="cancel"/>
      <alph/>
      <root/>
    </node>
    <node label="&#128259;" color="241">
      <speak what="repeat"/>
      <alph/>
      <root/>
    </node>
    <node label="&#182;" color="-1">
      <speak what="paragraph"/>
      <move forward="yes" dist="paragraph"/>
      <alph/>
      <node label="&#9114;&#182;" color="242">
        <delete forward="no" dist="paragraph"/>
        <delete forward="no" dist="char"/>
        <alph/>
        <root/>
      </node>
      <node  name="CTL_SPEAK_PARAGRAPH2" label="&#128483;&#182;" color="-1">
        <speak what="paragraph"/>
        <move forward="yes" dist="paragraph"/>
        <alph/>
        <ref name="CTL_SPEAK_PARAGRAPH2"/>
        <ref name="CTL_SPEAK"/>
      </node>
      <ref name="CTL_SPEAK"/>
    </node>
    <node label="&#128464;" color="-1">
      <speak what="all"/>
      <move forward="yes" dist="all"/>
      <alph/>
      <node label="&#9114;&#128464;" color="242">
        <delete forward="yes" dist="all"/>
        <delete forward="no" dist="all"/>
        <alph/>
        <root/>
      </node>
      <ref name="CTL_SPEAK"/>
    </node>
    <alph/>
  </node>

</control>
